#!/usr/bin/python3
# -*- coding: utf-8 -*-

"""
Compare results generate by faces.py
"""

__author__ = 'Benjamin Sientzoff'
__date__ = '4 november 2015'
__version__ = '0.1'
__license__ = "GNU GENERAL PUBLIC LICENSE V.2, June 1991"

import sys

def read_facit( facit_file_name ) :
    """
    Get the answer of a test from a file and store it in a dictionary
    
    :param facit_file_name: name of the file containing answer of the training set
    :return: dictionary storing for each images the answer
    """
    # open the file
    facit_f = open( facit_file_name, 'r' )
    # initiate a dictionary
    facit = {}
    # for each line
    for line in facit_f :
        # if the line contains a image name and the answer
        if line.startswith( "I" ) :
            # get the words on the line
            words = line.split()
            # create an entry in the dictionary with the image name
            # and convert to integer the answer associated
            facit[words[0]] = int( words[1] )
    # return the dictionary
    return facit
    
def cmp_res( arg1, arg2 ) :
    """
    Compare two resulta generated by faces
    
    :param arg1: first result to compare
    :param arg2: second result to compare
    :return: dictionnary containing for each images the two results, if different
    """
    diff = {}
    sum_total, sum_diff = 0., 0.
    for key in arg1 :
        sum_total += 1.
        if arg1[key] != arg2[key] :
            diff[key] = ( arg1[key], arg2[key] )
            sum_diff += 1
    if sum_diff > 0. :
        rate = sum_total / sum_diff
    else :
        rate = 0
    return diff, rate

if __name__ == "__main__" :
    res1 = read_facit( sys.argv[1] )
    res2 = read_facit( sys.argv[2] )
    diff, rate = cmp_res( res1, res2 )
    for k in diff :
        print( str( k + "  \t" + str( diff[k] ) ) )
        #print( str( k + "  \t" + diff[k][0] + "\t" + diff[k][0] ) )
    print( rate )

